import { useContext, useRef } from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import { ParallaxContext } from '../context/parallax/ParallaxContext'

import '../styles/Home.module.css'

const Home: NextPage = () => {

  const refContainer = useRef<HTMLDivElement>(null)
  const { scrollY } = useContext(ParallaxContext)

  let progress = 0

  const { current: elContainer } = refContainer

  if (elContainer) {
    progress = Math.min(1, scrollY / elContainer.clientHeight)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div ref={refContainer} className='min-h-screen flex flex-col items-center justify-center sticky top-0 -z-10'
        style={{
          transform: `translateY(-${progress * 20}vh)`
        }}
      >

        <div className='z-10 h-screen  w-full flex flex-col items-center justify-center text-7xl'>
          <div className='bg-gray-900/[.8] p-4 rounded-sm shadow-xl text-white'>
            Un texto apasionante
          </div>
        </div>
        <Image src='/assets/img/back.jpg' alt='Negocio en Osaka' layout='fill' className='absolute w-full h-full object-cover' />
      </div>
      <div className='h-screen bg-white px-4 flex justify-center pt-8'>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi commodi totam, unde modi corrupti minus officiis molestiae odio delectus, aperiam laborum! Sapiente dolor commodi suscipit sint atque officia ducimus odit.
      </div>


    </>
  )
}

export default Home


